### ISSUE TITLE
expose variable for additional eks map roles

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/delivery-aws-iac#105]
Similar to how [we expose adding additional user arns](https://github.com/defenseunicorns/iac/blob/main/modules/eks/variables.tf#L51-L59) to the aws-auth configmap via variable definition - it would be useful to expose the same for additional roles.

Propose adding:
```
variable "aws_auth_eks_map_roles" {
  description = "List of map of roles to add to aws-auth configmap"
  type = list(object({
    rolearn  = string
    groups   = list(string)
  }))
  default = []
}
```

And updating [the existing map roles](https://github.com/defenseunicorns/iac/blob/main/modules/eks/main.tf#L76-L87) to `concat` with the variable list.

**Comment by zack-is-cool** [comment]
This should be easier to implement after https://github.com/defenseunicorns/iac/issues/73 is completed

_new_ upstream [terraform-aws-eks implementation](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L461-L532)

**Comment by zack-is-cool** [comment]
you can modify this with the `aws_auth_roles` or `aws_admin_usernames` vars

https://github.com/defenseunicorns/terraform-aws-uds-eks/blob/58fee9931a7baedfa4ad39bf0f888db7b85c186e/variables.tf#L88-L92

here's an example of us adding the bastion's role to the `aws_auth_role` list
https://github.com/defenseunicorns/delivery-aws-iac/blob/main/examples/complete/main.tf#L85-L92

here's an example from the upstream module:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/complete/main.tf#L249-L288
