### ISSUE TITLE
Migrate away from blueprints for EKS Marketplace addons

### ISSUE THREAD

**Issue by zack-is-cool** [defenseunicorns/delivery-aws-iac#128]
We are currently configured to configure/install coredns, kubeproxy and ebs csi driver through aws blueprints. 

These should be moved away from blueprints and installed via the cluster_addons var that will be added

Need to investigate any additional configuration that blueprints may be doing with these addons. If there is none, we may not need to install coredns and kubeproxy, as those are installed by default on any eks cluster.

**Comment by zack-is-cool** [comment]
/test ping
This shouldn't do anything

**Comment by zack-is-cool** [comment]
this really shouldn't do anything

**Comment by ntwkninja** [comment]
IMO, if we don't need to customize the defaults, we can drop them entirely

**Comment by ntwkninja** [comment]
@zack-is-cool recommend closing this for now and revisiting when the blueprints migration is complete. thoguhts?

**Comment by zack-is-cool** [comment]
yeah, that's fine. 
I learned after creating this issue that for some `modules/kubernetes-addons` resources, blueprints is configurable to use either the eks marketplace addon or a helm chart and usually blueprints will handle some of the extra _aws-y_ things around using the addons/helm charts like setting up IRSA roles, etc.
