### ISSUE TITLE
Dynamically pivot based on availability in the region/AZ

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/delivery-aws-iac#133]
I'm seeing this error more often recently, such that it would likely be worth spending time on figuring out how to avoid it.

As a first pass I would want to either look at dynamically choosing either the instance type or the region or AZ

![image](https://user-images.githubusercontent.com/16000938/229578893-cf34ec20-1487-494b-b042-f5984e7ef50b.png)

**Comment by RothAndrew** [comment]
Tried a different region and got the same. This is becoming a bit of a blocker..

![image](https://user-images.githubusercontent.com/16000938/229592131-efdc1402-b8db-4d0b-a139-46bccbe5484c.png)

**Comment by zack-is-cool** [comment]
Maybe a different approach to this would be the mixed instance policy feature?

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/self_managed_node_group/main.tf#L114-L142

I think with this, we just feed it multiple instance types and it will use whatever is available
