### ISSUE TITLE
Add Module(s) to support AWS Workspaces

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#147]
- [Client](https://clients.amazonworkspaces.com/) used to connect
- authenticate with IAM 
- discovery on additional auth mechanisms (local PKI, Keycloak, etc.)

related to #148

**Comment by zack-is-cool** [comment]
A lot of good info in this doc:
https://docs.aws.amazon.com/whitepapers/latest/best-practices-deploying-amazon-workspaces/best-practices-deploying-amazon-workspaces.html

@ntwkninja I think that this scenario would probably match our usecase? We need an AD server to support workspaces. Do we want to roll our own AD or just use AWS's managed solution? Other users can exist in keycloak.
https://docs.aws.amazon.com/whitepapers/latest/best-practices-deploying-amazon-workspaces/scenario-3-standalone-isolated-deployment-using-aws-directory-service-in-the-aws-cloud.html
