### ISSUE TITLE
Research Spike: Integrate AWS Workspaces with Keycloak

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#148]
https://neuw.medium.com/aws-account-openid-federation-using-keycloak-40d22b952a43

https://docs.aws.amazon.com/workspaces/latest/adminguide/setting-up-saml.html

[This](https://aws.amazon.com/blogs/opensource/authenticating-with-amazon-managed-grafana-using-open-source-keycloak-on-amazon-eks/) is directly related but looks useful

[This](https://stackoverflow.com/questions/49810326/how-to-create-a-client-in-keycloak-to-use-with-aws-cognito-identity-federation) is a bit dated but may be an option

related to #147

**Comment by zack-is-cool** [comment]
More in-depth documentation exists in our coda site here
https://coda.io/workspaces/ws-InbWbJ6Pij/docs?search=workspaces%20spike

# spike notes
Some brief notes here on this research spike

A good portion of this process is manual, there aren't API calls for a good portion of the functionality for configuring Workspaces and Directory services. You need to work with the AWS GUI to configure
- FIPS mode AWS MSAD and workspaces connection
- Create users in the managed directory service (through the workspaces provisioning GUI)
	-  There are ways to work around this using ldappadd and a direct connection to AD, probably would be ideal if onboarding more than 5 users at a time (the gui limit) is not tenable

Interestingly, there is an [AWS cli command to reset user's passwords](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ds/reset-user-password.html)..?

Additionally, in AWS govcloud the SMTP functionality doesn't seem to work when you create users/workspaces. In AWS commercial, you're able to send emails to users via AWS to have users manage their own accounts/workspaces

## smart cards

> Amazon WorkSpaces supports the use of smart cards for both pre-session authentication and in-session authentication. **Pre-session authentication** refers to smart card authentication that's performed while users are logging in to their WorkSpaces. **In-session authentication** refers to authentication that's performed after logging in.

With workspaces, pre-session smart card authentication is only supported using AD Connector (from what I've gathered), meaning you cannot use Amazon Managed Directory Services to provide pre-session smart card authentication with workspaces.

In-session smart card authentication does work using the workspaces desktop client _after_ massaging AWS Managed AD GPOs for WSP clients and installing windows updates, Root certificates, Chrome browser. We have a (manual) process for creating a new "golden bundle" and using that for new workspaces users.

We tried out using SAML 2.0 Authentication with keycloak and self-registration, that works before getting to the actual workspaces login window (username and password)
see 1-6 here https://docs.aws.amazon.com/workspaces/latest/adminguide/amazon-workspaces.html#architecture

**Comment by ntwkninja** [comment]
@zack-is-cool are we good to close this?

**Comment by zack-is-cool** [comment]
I would say yes. Documentation on implementation of the solution in the environment has been completed.
