### ISSUE TITLE
Move VPC Module to its own Repo

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#167]
Per [this ADR](https://github.com/defenseunicorns/iac/discussions/146), move the VPC wrapper module to its own repo to be tested / versioned independently of other modules

AC:
- [ ] There is a product supported repo and we have updated our example to point to it
- [ ] refactor as necessary

**Comment by RothAndrew** [comment]
Same comment as in #171

**Comment by RothAndrew** [comment]
* "Code freeze" the existing VPC module directory
* Create repo `defenseunicorns/terraform-aws-uds-vpc`
* MIgrate the code
* Add rudimentary testing and docs
* Cut a release

**Comment by RothAndrew** [comment]
VPC module is mostly there. Waiting on Product to help me set up AWS access for the testing pipeline.
