### ISSUE TITLE
Move SOPS Module to its own Repo

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#168]
Per [this ADR](https://github.com/defenseunicorns/iac/discussions/146), move the SOPS module to its own repo to be tested / versioned independently of other modules

AC:
- [ ] There is a product supported repo and we have updated our example to point to it
- [ ] refactor as necessary

**Comment by RothAndrew** [comment]
Same comment as in #171

**Comment by wirewc** [comment]
Created the SOPS module repo, we're ready for @RothAndrew to migrate at his leisure.

**Comment by RothAndrew** [comment]
If nobody else picks it up before I get to it I'll grab it. Otherwise this should be considered up for grabs. The pattern has been established (see the vpc, bastion, and rds repos)
