### ISSUE TITLE
Move S3-IRSA Module to its own Repo

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#169]
Per [this ADR](https://github.com/defenseunicorns/iac/discussions/146), move the S3-IRSA module to its own repo to be tested / versioned independently of other modules

AC:
- [x] There is a product supported repo and we have updated our example to point to it
- [x] refactor as necessary

**Comment by RothAndrew** [comment]
Same comment as in #171

**Comment by wirewc** [comment]
Created https://github.com/defenseunicorns/terraform-aws-uds-s3-irsa and added the UDS team for access. 

@RothAndrew it's ready for the migration at your leisure.

**Comment by RothAndrew** [comment]
If nobody else picks it up before I get to it I'll grab it. Otherwise this should be considered up for grabs. The pattern has been established (see the vpc, bastion, and rds repos)

**Comment by RothAndrew** [comment]
The folder `modules/s3-irsa` needs to be deleted and the source line in the example root module needs to be updated to point to the new location.
