### ISSUE TITLE
Lockdown EKS Add-Ons Security Group

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#17]
https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/v4.24.0/examples/complete-kubernetes-addons/main.tf#L77-L100

edit: Implement EKS Blueprints production security group recommendations 

edit 2: How does this impact all the BB and mission app things (seems like we could define it for knowns but it could get complicated for unknowns)

**Comment by RothAndrew** [comment]
Link is dead. More detail needed in order to be able to pick this up and work it

**Comment by ntwkninja** [comment]
updated link
