### ISSUE TITLE
Move RDS Module to its own Repo

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#170]
Per [this ADR](https://github.com/defenseunicorns/iac/discussions/146), move the RDS module to its own repo to be tested / versioned independently of other modules

AC:
- [ ] There is a product supported repo and we have updated our example to point to it
- [ ] refactor as necessary

**Comment by RothAndrew** [comment]
Same comment as in #171

**Comment by wirewc** [comment]
Repo created: https://github.com/defenseunicorns/terraform-aws-uds-rds

**Comment by RothAndrew** [comment]
Working on this now. Should have a PR out later today.
