### ISSUE TITLE
Move Bastion Module to its own Repo

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#171]
Per [this ADR](https://github.com/defenseunicorns/iac/discussions/146), move the Bastion module to its own repo to be tested / versioned independently of other modules

AC:
- [ ] There is a product supported repo and we have updated our example to point to it
- [ ] refactor as necessary

**Comment by RothAndrew** [comment]
Since we have a spot for ADRs already, I recommend we make one there, rather than calling the discussion an ADR.

See [doc/adr](https://github.com/defenseunicorns/iac/tree/main/doc/adr)

**Comment by RothAndrew** [comment]
[This discussion[(https://github.com/defenseunicorns/iac/discussions/166) should come to a resolution before we do this.

**Comment by wirewc** [comment]
Repo created: https://github.com/defenseunicorns/terraform-aws-uds-bastion. 

The repo is ready for @RothAndrew to perform or assign the migration of this module.

**Comment by justin-o12** [comment]
We also have issue https://github.com/defenseunicorns/uds/issues/84.  This work might be duplicate effort.
