### ISSUE TITLE
EKS failing due to error with Windows AMI query

### ISSUE THREAD

**Issue by brianrexrode** [defenseunicorns/delivery-aws-iac#172]
We are starting to see this error when running `terraform apply` or `terraform destroy` for the eks module:
```
│ Error: Your query returned no results. Please change your search criteria and try again.
│
│   with module.eks.module.eks_blueprints.module.aws_eks_self_managed_node_groups["self_mg1"].data.aws_ami.predefined["windows"],
│   on .terraform/modules/eks.eks_blueprints/modules/aws-eks-self-managed-node-groups/data.tf line 17, in data "aws_ami" "predefined":
│   17: data "aws_ami" "predefined" {
```

I believe the issue is with the data resource specifying `owners = ["amazon"]` and the Windows image not belonging to the `amazon` owner.
Results (partial) from me running a query using `aws` cli `aws ec2 describe-images --filters "Name=name,Values=Windows_Server-2019-English-Core-EKS_Optimized-1.23-*"`
```
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2023-03-20T19:37:59.000Z",
            "ImageId": "ami-0c45f04ec51148b9b",
            "ImageLocation": "055183720277/Windows_Server-2019-English-Core-EKS_Optimized-1.23-2023.03.15",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "055183720277",
```
Notice the `ImageLocation` and `OwnerId`

Same query but with `--owners amazon` 
`aws ec2 describe-images --owners amazon --filters "Name=name,Values=Windows_Server-2019-English-Core-EKS_Optimized-1.23-*"`
```
`{
    "Images": []
}
```

Same query but for the amazon linux ami
`aws ec2 describe-images --owners amazon --filters "Name=name,Values=amazon-eks-node-1.23-*"`
```
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2022-09-27T11:53:21.000Z",
            "ImageId": "ami-08897d562ccb974ea",
            "ImageLocation": "amazon/amazon-eks-node-1.23-v20220926",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "151742754352",
```
Again, notice the `ImageLocation` and `OwnerId`

As I'm writing this, I believe this is probably an upstream issue with eks_blueprints

**Comment by blancharda** [comment]
Worth noting that I think something changed in AWS itself.

I watched the behavior change..
It worked on Tuesday and failed on Wednesday with no changes to my local TF environment or cluster(s)

**Comment by blancharda** [comment]
Temporary workaround is to comment out the windows AMI in your local .terraform folder.
Comment out `.terraform/modules/valid_eval.eks.eks_blueprints/modules/aws-eks-self-managed-node-groups/locals.tf:#59` to remove the windows provider from the list.

Milage may vary...

**Comment by ntwkninja** [comment]
blueprints module no longer utilized, please reopen if you see anything on the new upstream module
