### ISSUE TITLE
Add zarf init test to EKS

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#174]
As an iac / UDS user, I would like to like to know which EKS versions are compatible with zarf and supported.

Recommendation: ~~add a zarf init e2e test for validating this functionality.~~ Add a temporary zarf init smoke test to validate (until there is a zarf package iac that does this)

Note: `zarf init` should take place after all terraform resources have been provisioned so the `ignore` labels are placed on existing resources. Otherwise, zarf could come up before an EKS add-on and will own that resource but the image won't be available in the zarf registry.

**Comment by wirewc** [comment]
I think I might have a Zarf package for this. 

TODO: Follow up in 1 week.

**Comment by ntwkninja** [comment]
any updates @wirewc ?

**Comment by ntwkninja** [comment]
Additional context regarding storage classes related to `zarf init`

When EFS is set as the default storage class, gitea fails to deploy. We could work around this / possibly work that into a zarf contribution.

```
# k logs -n zarf zarf-gitea-0

Defaulted container "gitea" out of: gitea, init-directories (init), init-app-ini (init), configure-gitea (init)
Error from server (BadRequest): container "gitea" in pod "zarf-gitea-0" is waiting to start: PodInitializing

# k logs -n zarf zarf-gitea-0 -c init-directories

+ chown 1000:1000 /data
chown: /data: Operation not permitted
```

```
# gitea statefulset

  initContainers:
  - command:
    - /usr/sbin/init_directory_structure.sh
```

https://github.com/defenseunicorns/zarf/blob/main/packages/gitea/gitea-values.yaml#L19

**Comment by wirewc** [comment]
@ntwkninja I was out last week and just seeing this message now. No there is not any movement on this yet.

**Comment by ntwkninja** [comment]
> Additional context regarding storage classes related to `zarf init`
> 
> When EFS is set as the default storage class, gitea fails to deploy. We could work around this / possibly work that into a zarf contribution.

https://github.com/defenseunicorns/zarf/pull/1706
