### ISSUE TITLE
EPIC: Add STIG / NIST 800-53 Controls

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#183]
### Persona

As a consumer of this capability, I need to understand which security controls and STIG checklist items are applicable / satisfied, as well as, understand what software is consumed here.

### Description

Provide documentation or a ReadMe to capture security controls, STIG checklist and software list.

### Use Case

To help accelerate the ATO and inform lula validations.

### Impact

Slower adoption, confusion on value proposition and not understanding the purpose of this capability.

### Completion

security controls, STIG checklist and software list are captured in a document (MVP)

**Comment by Tobyhb** [comment]
Link to Unicorn Security Controls: https://docs.google.com/spreadsheets/d/1wq3G_xAC04L9j92Fime_ycSxMXswlfPO/edit#gid=52300737

**Comment by ntwkninja** [comment]
We need to identify the controls that are partially satisfied by iac as an OSCAL component / catalogue. Discovery is needed around how we capture this (read, high level framework).

- Identify controls (controls matrix)
- document in OSCAL format
- verify with lula

**Comment by ntwkninja** [comment]
ToDo: migrate to UDS IaC repos 

tracking
