### ISSUE TITLE
Include GovCloud in our test suite

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/delivery-aws-iac#239]
### Persona

A user of this terraform code that uses AWS GovCloud

### Description

Stuff that works fine in AWS Commercial doesn't work in GovCloud. See #228 

### Use Case

GovCloud is where most of our real customers will be using this work

### Impact

The pipeline will continue to be non-definitive for any user that is using GovCloud instead of Commercial

### Completion

The same test suite that we currently being run in AWS Commercial is also run in AWS GovCloud

**Comment by RothAndrew** [comment]
https://github.com/defenseunicorns/delivery-aws-iac/issues/228#issuecomment-1542688138

**Comment by ntwkninja** [comment]
> [#228 (comment)](https://github.com/defenseunicorns/delivery-aws-iac/issues/228#issuecomment-1542688138)
> 
> > Problem 1 - In AWS GovCloud, [enable_efs=true](https://github.com/defenseunicorns/delivery-aws-iac/blob/main/examples/complete/fixtures.common.tfvars?rgh-link-date=2023-05-10T19%3A21%3A39Z#L86) does not provision a file system as intended due to permissions in the IAM policy attached to the EFS service account role.
> > Problem 2 - In AWS GovCloud, when a PVC is invoked by a pod the EFS file system policy does not allow an EFS access point to be created (could also be related to # 1 but is a separate issue).
> > Feature Request: Add FIPS VPC endpoint for EFS and configure EFS to use it
> > 
> > * edit: [repo1.dso.mil/big-bang/bigbang/-/issues/1463](https://repo1.dso.mil/big-bang/bigbang/-/issues/1463)

after looking into this further:

Problem 1: The EFS service account isn't the entity that provisions the EFS file system, that is accomplished via the IAM role applying the terraform (occurs before the efs-csi-driver is provisioned). I suspect the bastion does not have sufficient IAM permissions to create an EFS filesystem.

Problem 2: I suspect this is directly related to # 1
