### ISSUE TITLE
ADR: Create k8s backend for terraform

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#24]
https://developer.hashicorp.com/terraform/language/settings/backends/kubernetes

This issue is to create an ADR to help frame the options we have for terraform state, as well as, help provide tangible examples that will help inform a potential common UDS pattern instantiation and recovery operations in connected, semi-connected and airgapped environments.

Related / complimentary work: the KV pair methodology that @wirewc is working

Option 1: Use S3 tf state backend (could be copied into the cluster via a k8s cron job)

Option 2: Use local tf state (can be copied to a k8s PV via EC2 cron job)

Option 3: Use k8s tf state backend & k8s cron job to backup to S3

**Comment by RothAndrew** [comment]
@JaseKoonce since you self-assigned it I assume you and @ntwkninja got together in person and figured out what needs to be done here.

If we can get that detail added here that would be great.

**Comment by JaseKoonce** [comment]
@RothAndrew, @ntwkninja and I talked briefly about it and the way that I understand this going forward is to leverage the Kubernetes Lease resource for state locking. In addition to this we will be setting up an S3 bucket for scheduled backups of the remote state. @ntwkninja, please let me know if I missed anything or misunderstood the goals for this issue.

**Comment by RothAndrew** [comment]
Not sure I'm following. Hopefully the ADR will provide more light. That's being worked first yes?

**Comment by ntwkninja** [comment]
@JaseKoonce we can experiment in [this repo](https://github.com/defenseunicorns/terraform-k8s-tfstate-backend) while we work potential use cases.

**Comment by ntwkninja** [comment]
update the issue to include a description (previously just had the link and no contents / context)

**Comment by JaseKoonce** [comment]
Some condensed thoughts about using option 3:

### Cons:
- Adds complexity
- Currently requires user input to attach the policy to the service account ( Working through this currently)

### Pros
- Failure resistance
- Recovery would be relatively simple

**Comment by wirewc** [comment]
@ntwkninja my kv pair thing does not have an official plan for when to be included.
