### ISSUE TITLE
Terraform does not properly configure eniconfig resource

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#245]
In GovCloud during repeat build attempts, terraform failed to properly build the eniconfigs resource resulting in pods being unable to schedule on worker nodes in us-gov-east-1a & 1c regions.

What I expected to happen: the us-gov-east-1a & 1c eniconfigs would be associated to the corresponding intra_subnets for those regions.

What actually happened: the intra_subnet for us-gov-east-1a was assigned to the us-gov-east-1c eniconfig and vice versa

What is needed to reproduce: run `terraform apply -target=module.eks` from the bastion (vpc and bastion were provisioned in a previous disconnected step)

Workaround: I was able to `kubectl edit eniconfigs.crd.k8s.amazonaws.com us-gov-east-1a` and manually assign the correct subnet to allow pods to schedule on the worker node in that availability zone (repeat for worker in 1b az)

edit: suspect misconfiguration in the eks module `k8s-manifests.tf`

**Comment by zack-is-cool** [comment]
Can you give an example of where in the manifest is misconfigured and how it was fixed manually?

**Comment by ntwkninja** [comment]
need to duplicate / capture additional context

**Comment by zack-is-cool** [comment]
from a lab cluster more context:

```yaml
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"crd.k8s.amazonaws.com/v1alpha1","kind":"ENIConfig","metadata":{"annotations":{},"name":"us-west-2a"},"spec":{"securityGroups":["sg-0c9bd24c517595f17","sg-0e3ed5adc9649605d","sg-0f9c1c6ea817aa142"],"subnet":"subnet-0b1366579255c5835"}}
  creationTimestamp: "2023-04-26T19:10:59Z"
  generation: 1
  name: us-west-2a
  resourceVersion: "1015"
  uid: f7d9edef-89d6-462e-bf5b-b93dd72d3388
spec:
  securityGroups:
  - sg-0c9bd24c517595f17
  - sg-0e3ed5adc9649605d
  - sg-0f9c1c6ea817aa142
  subnet: subnet-0b1366579255c5835
```

Documentation on eniconfig
Tutorial: Custom networking - Amazon EKS
https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html#custom-networking-configure-kubernetes
https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html#custom-networking-annotate-eniconfig

Nice workshop on vpc-cni:
https://www.eksworkshop.com/docs/networking/custom-networking/vpc

From the documentation above, you either need to have the `name` of the `ENIConfig` match a subnet in the az or you need to annotate the nodes. We only have one subnet per az, so we can just ensure that the subnets match the az,

@ntwkninja side note, I found that there's another option of creating the eniconfigs through the addon (really helm chart). This would allow us to not use kubectl provider and _technically_ configure it through the aws api
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/values.yaml#L151-L169
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/templates/eniconfig.yaml

do we want to explore this?

**Comment by zack-is-cool** [comment]
nice lil test:
```bash
### bash -> terraform
#!/bin/bash
unset DEMO_HOME
DEMO_HOME=$(mktemp -d)

pushd "$DEMO_HOME" || exit 1

cat <<'EOF' >test.tf
# Fetch subnet details
variable "subnet_ids" {
  description = "List of subnet ids"
  type        = list(string)
  default     = ["subnet-0b1366579255c5835", "subnet-0a7df838f6e1cb9ea", "subnet-0473c490737dc17e5"]
}

data "aws_subnet" "selected" {
  for_each = toset(var.subnet_ids)
  id       = each.key
}

# Define a local value for the manifest template
locals {
  manifest_template = <<TEMPLATE
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: %s
spec:
  subnet: %s
  securityGroups:
  %s
TEMPLATE
}

# Generate the manifest
output "eni_config" {
  value = { for id, subnet in data.aws_subnet.selected :
    id => format(
      local.manifest_template,
      id,
      subnet.availability_zone,
      indent(2, join("\n", [for sg in ["sg1", "sg2"] : "- ${sg}"]))
    )
  }
}

EOF

AWS_REGION=us-west-2 ave du-dev terraform init
AWS_REGION=us-west-2 ave du-dev terraform apply -auto-approve

popd > /dev/null 2>&1
while (( $? == 0 )); do popd  > /dev/null 2>&1; done #popd looper
rm -rf "$DEMO_HOME";
###
```

```logs

Outputs:

eni_config = {
  "subnet-0473c490737dc17e5" = <<-EOT
  apiVersion: crd.k8s.amazonaws.com/v1alpha1
  kind: ENIConfig
  metadata:
    name: subnet-0473c490737dc17e5
  spec:
    subnet: us-west-2c
    securityGroups:
    - sg1
    - sg2
  
  EOT
  "subnet-0a7df838f6e1cb9ea" = <<-EOT
  apiVersion: crd.k8s.amazonaws.com/v1alpha1
  kind: ENIConfig
  metadata:
    name: subnet-0a7df838f6e1cb9ea
  spec:
    subnet: us-west-2b
    securityGroups:
    - sg1
    - sg2
  
  EOT
  "subnet-0b1366579255c5835" = <<-EOT
  apiVersion: crd.k8s.amazonaws.com/v1alpha1
  kind: ENIConfig
  metadata:
    name: subnet-0b1366579255c5835
  spec:
    subnet: us-west-2a
    securityGroups:
    - sg1
    - sg2
  
  EOT
}
```
