### ISSUE TITLE
tigera operator fails kyverno policy / validating webhook once bigbang is installed

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#247]
If the calico addon is deployed as currently configured, it will be blocked by a kyverno policy once big bang is deployed.

Since Calico or a similar CNI addon is needed to enable netpol enforcement on EKS, we should do one of the following.

1. Use the iron bank image for the tigera operator (requires IB creds in IaC pipeline... we currently don't need them)
2. Move tigera-operator to DUBBD-AWS
3. Leave it as is but specify an optional variable `use-ib-images: true` for IB creds & IB image

~~I think we'd like to go with the first option for now so long as the tigera-operator iron bank image is being actively managed~~

**Comment by ntwkninja** [comment]
team voted to leave it as is but specify an optional variable use-ib-images: true for IB creds & IB image (# 3)

**Comment by zack-is-cool** [comment]
calico has been removed
