### ISSUE TITLE
Configure Renovate to monitor versions in our examples / vars

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#255]
We should pin & test specific versions of non-AWS EKS Add-Ons, zarf, etc. and have renovate monitor the upstream for new releases

- [This](https://github.com/defenseunicorns/delivery-aws-iac/blob/main/examples/complete/fixtures.common.tfvars#L94-L116) is where we're currently specifying EKS add-on versions

- [zarf version
](https://github.com/defenseunicorns/delivery-aws-iac/blob/main/examples/complete/fixtures.common.tfvars#L26)

- [EKS version
](https://github.com/defenseunicorns/delivery-aws-iac/blob/main/examples/complete/fixtures.common.tfvars#L31)

Note: AWS addons are using the latest available for a particular EKS release because they are built / tested in the AWS release process.

**Comment by RothAndrew** [comment]
I believe ideally we'd use the same pattern that is documented here: https://docs.renovatebot.com/modules/manager/regex/#advanced-capture

Here's an example of it being used currently:
* https://github.com/defenseunicorns/delivery-aws-iac/blob/509fee6fe638d6a896d68fa53654d7a9e14588ee/renovate.json5#L39
* https://github.com/defenseunicorns/delivery-aws-iac/blob/509fee6fe638d6a896d68fa53654d7a9e14588ee/.env#L2

**Comment by ntwkninja** [comment]
How can we track EKS releases?

**Comment by ntwkninja** [comment]
@jacobbmay if it's not too much trouble, could you take a look at the current warning as well? Looks like it hasn't pulled an update since 9 May

> Renovate failed to look up the following dependencies: Failed to look up github-tags package bridgecrewio/checkov.

**Comment by RothAndrew** [comment]
https://github.com/renovatebot/renovate/discussions/21962
