### ISSUE TITLE
Add terraform to bastion user_data

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#258]
As a consumer of this repository, I would like the ability to apply terraform from the bastion (i.e. EKS cluster in secure mode). This would likely be an iterative step until a zarf package for IaC (which has the binary) is published / available.

We have an ec2 IAM role and policy for terraform to be applied within a secure environment and it would be nice to have the terraform binary installed by the user_data or zarf or something else.

**Comment by RothAndrew** [comment]
Just throwing another idea out there: What if we updated the user_data to install docker (or equivalent like podman) and pulled the [build-harness](https://github.com/defenseunicorns/not-a-build-harness) in?

**Comment by ntwkninja** [comment]
could be ok if we had a build harness with a minimal set of dependencies (i.e. chainguard base image with only needed tooling)

The more things we bring in the more pain we experience from an ATO perspective

**Comment by ntwkninja** [comment]
tools are generally ok to bring in but it seems very squishy how those are defined

@Tobyhb probably has better insights

**Comment by ntwkninja** [comment]
no issues with build harness in its current implementation

**Comment by ntwkninja** [comment]
closing this issue since zarf will handle dependency management of needed binaries eventually.

users will have to management this dependency by exception in the interim.
