### ISSUE TITLE
Issues with a conflict between the auto-tag workflow and ReleasePlease bot

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/delivery-aws-iac#317]
### Persona

Maintainer of this repo

### Description

We have an `auto-tag` GHA workflow that creates a new tag on every push to main. We also have the ReleasePlease bot that does similar things. There is no good understanding at the team level as to how we want to handle automatic releases.

### Use Case

Having tags with 2 different formats is confusing to maintainers and downstream automation.

### Impact

If this is not addressed we will continue to have 2 competing methods of automatic releases creating tags in 2 different formats.

### Completion

- An ADR has been written and approved describing how we as a team want our automated release process to work.
- The GHA workflows and/or ReleasePlease configuration has been updated to reflect the decision.

### Additional Context

none

**Comment by ntwkninja** [comment]
Great idea to capture this in and ADR. Below are the closest things we have to one currently:

- #271 & [PR](https://github.com/defenseunicorns/delivery-aws-iac/pull/306/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) that closed issue

The intent is to migrate all modules to their own repo, which will have independent testing & releases. This repo's purpose is both a comprehensive root module example that consumes those independent modules to help inform how they are intended to be used and validation of functionality across multiple dependencies / upstream modules that update on disparate cadences.
