### ISSUE TITLE
Upgrade to EKS v1.26

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#53]
pending [upstream containerd issue](https://github.com/awslabs/amazon-eks-ami/issues/1162)

**Comment by ntwkninja** [comment]
EKS v1.24 & v1.25 currently use containerd version 1.6.6

**Comment by RothAndrew** [comment]
Related to #81 #93

**Comment by ntwkninja** [comment]
![image](https://user-images.githubusercontent.com/70963120/230549463-fed378b4-81c1-40dd-a299-e2237bb10f65.png)

**Comment by ntwkninja** [comment]
On a related note: [This PR](https://github.com/awslabs/amazon-eks-ami/pull/1252) could help with updating containerd (or other EKS dependencies) in the future as a workaround while upstream does their thing. It allows us to make build the images using the same process that upstream uses but having control over some [dependencies](https://github.com/awslabs/amazon-eks-ami/blob/v20230322/eks-worker-al2-variables.json)

**Comment by RothAndrew** [comment]
![Image](https://user-images.githubusercontent.com/16000938/231276735-0fd2c8e5-0bbf-492e-a165-e2436d032be0.png)

**Comment by ntwkninja** [comment]
@blancharda @brianrexrode is there a need to have an upgrade path or could we jump straight to v1.26?

**Comment by blancharda** [comment]
I believe EKS only supports sequential updates -- so it would be nice to provide a path for people (like me 😇) who are currently on 1.24.

**Comment by RothAndrew** [comment]
> @blancharda @brianrexrode is there a need to have an upgrade path or could we jump straight to v1.26?

The module has an input for the kubernetes version. Currently the only valid value is `1.23`, but as we test more versions we should add more values to the list of valid ones.

I don't think this is as much about leaving out the other versions (1.24, 1.25), but rather choosing which one to test and support first past 1.23, and incrementally choosing to support and test the other versions as we have capacity (and feedback that they are needed)

At some point we are going to want to drop support for older versions, or our test suite (and the required logic to work with the various versions) will grow to unsustainable levels.

**Comment by wirewc** [comment]
I was talking to @zachariahmiller about this a bit. I think we need something as this may happen again in the future so this needs to be on a road map.

**Comment by jeff-mccoy** [comment]
This was also a bit of a unique problem where a  CRI bug broke a core concept of zarf, and distros are often very slow to upgrade CRI

**Comment by brianrexrode** [comment]
I just did a clean deployment of EKS 1.26 using `v0.0.0-alpha.9` of our IaC repo. 

Just a heads up:

for the eks-addon `aws-node-termination-handler` helm_addon module, PodSecurityPolicies (PSP) have been replaced with Pod Security Admission (PSA) as noted [here](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#:~:text=.-,Important,-PodSecurityPolicy%20(PSP)%20is) so this addon currently fails.

Also got this Warning
``` Warning: "default_secret_name" is no longer applicable for Kubernetes v1.24.0 and above``` from the same addon
