### ISSUE TITLE
ADR: Hardened EKS AMI

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/delivery-aws-iac#56]
[Building STIG-compliant amis for EKS](https://aws.amazon.com/blogs/containers/building-stig-compliant-amis-for-amazon-eks/)

- Consider using [Amazon Linux 2 CIS STIG](https://www.cisecurity.org/cis-hardened-images/amazon/) ami & adding the EKS binaries
- Consider using [bottlerocket](https://github.com/bottlerocket-os/bottlerocket/) AMI eventually

Related Issues:
[FIPS EKS AMI issue](https://github.com/awslabs/amazon-eks-ami/issues/1002)
[FIPS Bottlerocket issue](https://github.com/bottlerocket-os/bottlerocket/issues/1667)

Edit: EC2 image builder is inconsistent for things in the user_data and if we're going to do something custom, we may want to consider packer.

Definition of Done:
 - [ ] ADR decision has been recorded

**Comment by RothAndrew** [comment]
Is this meant to be a research spike/ADR? Or to actually change which AMI is used by the examples?

Currently:
* It doesn't seem like the module(s) have any say or care what AMI is being used. The examples pass in the nodegroup definitions which will include which AMI to use
* The examples currently use Amazon Linux 2 (the regular one that everyone uses)

Notes:
* If we want the modules to be "secure by default" they should somehow specify which AMI is used. If we need it to be overridable then IMO we should have some kind of `allow_insecure_vars = true` variable.

**Comment by ntwkninja** [comment]
Yes, was intended to be a research spike.

Also, agree @RothAndrew 

I think there would be a lot of benefit to standardizing on an aws-supported distroless AMI for EKS (bottlerocket) and allowing users to set the flag mentioned if they prefer a different option.

**Comment by ntwkninja** [comment]
This [PR](https://github.com/defenseunicorns/delivery-aws-iac/pull/263) added bottlerocket node group example
